---
- hosts: localhost
  tasks:
  - name: Ensure dotfiles repository is cloned locally.
    git:
      repo: "https://github.com/skrzepto/dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      update: yes
      force: yes
    become: no

- include: tasks/main.yml
- include: tasks/git.yml
- include: tasks/gnome-terminal.yml
- include: tasks/i3wm.yml
- include: tasks/zsh.yml
- include: tasks/vim.yml
- include: tasks/multimedia.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- include: tasks/java.yml
- include: tasks/smartgit.yml
- include: tasks/idea-community.yml
- include: tasks/eclipse.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
