---
- hosts: localhost
  tasks:
  - name: Ensure dotfiles repository is cloned locally.
    git:
      repo: "https://github.com/skrzepto/dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      update: yes
      force: yes
    become: no

- import_playbook: tasks/main.yml
- import_playbook: tasks/git.yml
- import_playbook: tasks/i3wm.yml
- import_playbook: tasks/zsh.yml
- import_playbook: tasks/vim.yml
- import_playbook: tasks/python.yml