---
- hosts: localhost
  tasks:

  - name: Clone gnome-terminal-colors-solarized theme
    git:
      repo: https://github.com/Anthony25/gnome-terminal-colors-solarized.git
      dest: "{{ lookup('env', 'HOME') }}/.gnome-terminal-colors-solarized"

  - name: Install Solarized theme
    shell: "{{ lookup('env', 'HOME') }}/.gnome-terminal-colors-solarized/install.sh --scheme=dark --skip-dircolors <<< $'1\nyes\n'"
