---
- hosts: localhost
  tasks:
  - name: Install I3WM
    dnf:
      name:
      - i3
      - i3lock
      state: present
    become: true
    become_user: root

  - name: Linking i3config
    file: src="{{ lookup('env', 'HOME') }}/.dotfiles/i3/i3config/base" dest="{{ lookup('env', 'HOME') }}/.config/i3/config" state=link force=yes

  - name: Linking i3status
    file: src="{{ lookup('env', 'HOME') }}/.dotfiles/i3/i3status/base" dest="{{ lookup('env', 'HOME') }}/.config/i3/i3status.conf" state=link force=yes
