---
- hosts: localhost
  vars:
      idea_community_url: "https://download.jetbrains.com/idea/ideaIC-2016.3.5.tar.gz"
      idea_community_sha: "sha256:85da1e81036968c272b66f6e4d62c117455352ebc769692742a6abfc97ecbc6c"
  tasks:
    - name: download jetbrains idea community and check (sha256)
      get_url:
        url: "{{ idea_community_url }}"
        dest: "{{ lookup('env', 'HOME') }}/Downloads/ideaIC.tar.gz"
        checksum: "{{ idea_community_sha }}"

    - name: Get dir 1 - fast - when you are sure that there is one and only one subfolder
      shell: tar tf "{{ lookup('env', 'HOME') }}/Downloads/ideaIC.tar.gz" | head -1 | sed -e 's/\/.*//'
      changed_when: false
      register: tar_folder_name

    - debug: 'msg="Subfolder: {{tar_folder_name.stdout}}"'

    - name: unarchive jetbrains idea community
      # Unarchive a file that is already on the remote machine
      unarchive:
        src: "{{ lookup('env', 'HOME') }}/Downloads/ideaIC.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/Apps/"
        remote_src: True

    - name: link jetbrains idea community binary to /usr/local/bin
      file: dest="/usr/local/bin/idea" src="{{ lookup('env', 'HOME') }}/Apps/{{ tar_folder_name.stdout }}/bin/idea.sh" state=link force=yes
      become: true
      become_user: root
