---
- hosts: localhost
  tasks:
    - name: Install base packages
      dnf: name={{item}} state=present
      with_items:
        - redshift
        - network-manager-applet
        - htop
        - pavucontrol
        - xclip
        - thunar
        - nautilus
        - file-roller
        - tmux
        - git
        - gedit
        - neovim
        - python2-neovim
        - python3-neovim
        - shutter
        - xarchiver
        - emacs
        - glances
        - keepassxc
        - golang
        - arandr
        - syncthing
        - lxterminal
        - scrot
        - xbacklight
        - redshift-gtk
        - exa
        - ripgrep
        - rsync
        - ranger
        - fd-find
      become: true
      become_user: root

    - name: Install communication applications
      dnf: name={{item}} state=present
      with_items:
        - evolution
        - hexchat
        # - mumble
      become: true
      become_user: root

    - name: Install office / pdf
      dnf: name={{item}} state=present
      with_items:
        - libreoffice
        - evince
        - mupdf
      become: true
      become_user: root
