---
- hosts: localhost
  tasks:
    - name: Install base packages
      dnf: 
        name: 
        - redshift 
        - network-manager-applet 
        - htop 
        - pavucontrol 
        - xclip 
        - thunar 
        - nautilus 
        - file-roller 
        - tmux 
        - git 
        - gedit 
        - neovim 
        - python3-neovim 
        - shutter 
        - xarchiver 
        - emacs 
        - glances 
        - keepassxc 
        - golang 
        - arandr 
        - syncthing 
        - lxterminal 
        - scrot 
        - xbacklight 
        - redshift-gtk 
        - exa 
        - ripgrep 
        - rsync 
        - ranger 
        - fd-find 
        - copyq 
        - fzf
        state: present
      become: true
      become_user: root

    - name: Install communication applications
      dnf:
        name:
        - evolution
        - hexchat
        # - mumble
        state: present
      become: true
      become_user: root

    - name: Install office / pdf
      dnf:
        name:
        - libreoffice
        - evince
        - mupdf
        state: present
      become: true
      become_user: root