---
- hosts: localhost
  tasks:
  - name: Install rpmfussion repo
    dnf: name={{item}} state=present
    with_items:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm 
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    become: true
    become_user: root
    
  - name: Install cmus
    dnf: name={{item}} state=present
    with_items:
      - cmus
      - youtube-dl
      - ffmpeg
      - ffmpeg-devel
    become: true
    become_user: root
