---
- hosts: localhost
  vars:
      smartgit_url: "http://www.syntevo.com/static/smart/download/smartgit/smartgit-linux-17_0_2.tar.gz"
      smartgit_sha: "sha1:6678adcc8e58a44727291fc52cdbe87829d1b64d"
  tasks:
    - name: Install Java jdk
      yum: name={{item}} state=installed
      with_items:
        - java-1.8.0-openjdk
      become: true
      become_user: root

    - name: download smargit and check (sha)
      get_url:
        url: "{{ smartgit_url }}"
        dest: "{{ lookup('env', 'HOME') }}/Downloads/smartgit.tar.gz"
        checksum: "{{ smartgit_sha }}"

    - name: unarchive smartgit
      # Unarchive a file that is already on the remote machine
      unarchive:
        src: "{{ lookup('env', 'HOME') }}/Downloads/smartgit.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/Apps/"
        remote_src: True

    - name: link smartgit binary to /usr/local/bin
      file: dest="/usr/local/bin/smartgit" src="{{ lookup('env', 'HOME') }}/Apps/smartgit/bin/smartgit.sh" state=link force=yes
      become: true
      become_user: root
