---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install shell packages
    yum: name={{item}} state=present
    with_items:
      - zsh
    become: true
    become_user: root

  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - name: remove standard zshrc
    file: dest="{{ lookup('env', 'HOME') }}/.zshrc" state=absent

  - name: symlink zshrc
    file: dest="{{ lookup('env', 'HOME') }}/.zshrc" src="{{ lookup('env', 'HOME') }}/.dotfiles/zsh/zshrc" state=link force=yes

  - name: Make zsh default
    shell: chsh -s /bin/zsh
