---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install shell packages
    dnf:
      name:
      - zsh
      - util-linux-user
      state: present
    become: true
    become_user: root

  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - name: remove standard zshrc
    file: dest="{{ lookup('env', 'HOME') }}/.zshrc" state=absent

  - name: symlink zshrc
    file: dest="{{ lookup('env', 'HOME') }}/.zshrc" src="{{ lookup('env', 'HOME') }}/.dotfiles/zsh/zshrc" state=link force=yes

  - name: Make zsh default for root user
    shell: chsh -s /bin/zsh
    become: true

  - name: Make zsh default for current user
    shell: chsh -s $(which zsh) $(whoami)
    become: true